name: flutter_secure_file_storage
description: An implementation for flutter secure file storage. For example keychain has a soft limit of 4kb. Using the file system instead we can store much larger content
version: 0.1.0
homepage: https://github.com/icapps/flutter_secure_file_storage

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  async: ^2.9.0
  flutter:
    sdk: flutter
  flutter_key_value_file_storage: ^0.0.5
  flutter_secure_storage: ^6.0.0
  path: ^1.8.1
  path_provider: ^2.0.11
  pointycastle: ^3.6.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mockito: ^5.2.0

flutter:
  plugin:
    platforms:
      android:
        package: com.icapps.flutter_secure_file_storage
        pluginClass: SecureFileStoragePlugin
      ios:
        pluginClass: FlutterSecureFileStoragePlugin
